services:
  - type: web
    name: gemini-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: true
